//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/cthfvrl/Code/hw/ide-dev/PascalLexer/antlr/Grammar.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class Grammar : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Number=1, Identifier=2, CharacterString=3, Symbol=4, Whitespace=5;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"Number", "Sign", "UnsignedInteger", "UnsignedReal", "ScaleFactor", "Plus", 
		"Minus", "Dollar", "Ampersand", "Percent", "Dot", "E", "DigitSequence", 
		"BinSequence", "HexSequence", "OctalSequence", "Digit", "Hex", "Octal", 
		"Bin", "Identifier", "Letter", "Underscore", "CharacterString", "QuotedString", 
		"Quote", "ControlString", "Hash", "Symbol", "Whitespace"
	};


	public Grammar(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Grammar(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "Number", "Identifier", "CharacterString", "Symbol", "Whitespace"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Grammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Grammar() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\a', '\xBF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x5', '\x2', '\x41', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x5', '\x2', '\x45', '\n', '\x2', '\x3', '\x3', '\x3', '\x3', '\x5', 
		'\x3', 'I', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x5', '\x4', 'U', '\n', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '[', '\n', '\x5', '\x3', 
		'\x5', '\x5', '\x5', '^', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', '\x5', 
		'\x6', '\x62', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x6', '\xE', 'u', '\n', '\xE', '\r', 
		'\xE', '\xE', '\xE', 'v', '\x3', '\xF', '\x6', '\xF', 'z', '\n', '\xF', 
		'\r', '\xF', '\xE', '\xF', '{', '\x3', '\x10', '\x6', '\x10', '\x7F', 
		'\n', '\x10', '\r', '\x10', '\xE', '\x10', '\x80', '\x3', '\x11', '\x6', 
		'\x11', '\x84', '\n', '\x11', '\r', '\x11', '\xE', '\x11', '\x85', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x5', 
		'\x16', '\x92', '\n', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\a', '\x16', '\x97', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\x9A', 
		'\v', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x19', '\x3', '\x19', '\x6', '\x19', '\xA2', '\n', '\x19', '\r', 
		'\x19', '\xE', '\x19', '\xA3', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\a', '\x1A', '\xAB', '\n', '\x1A', '\f', 
		'\x1A', '\xE', '\x1A', '\xAE', '\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', 
		'\x5', '\x1E', '\xBC', '\n', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x2', 
		'\x2', ' ', '\x3', '\x3', '\x5', '\x2', '\a', '\x2', '\t', '\x2', '\v', 
		'\x2', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', '\x13', '\x2', '\x15', 
		'\x2', '\x17', '\x2', '\x19', '\x2', '\x1B', '\x2', '\x1D', '\x2', '\x1F', 
		'\x2', '!', '\x2', '#', '\x2', '%', '\x2', '\'', '\x2', ')', '\x2', '+', 
		'\x4', '-', '\x2', '/', '\x2', '\x31', '\x5', '\x33', '\x2', '\x35', '\x2', 
		'\x37', '\x2', '\x39', '\x2', ';', '\x6', '=', '\a', '\x3', '\x2', '\n', 
		'\x4', '\x2', 'G', 'G', 'g', 'g', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\x32', ';', '\x43', 'H', '\x63', 'h', '\x3', '\x2', '\x32', '\x39', '\x3', 
		'\x2', '\x32', '\x33', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x4', 
		'\x2', '\f', '\f', ')', ')', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', 
		'\"', '\x2', '\xBC', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '@', '\x3', '\x2', '\x2', '\x2', '\x5', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\a', 'T', '\x3', '\x2', '\x2', '\x2', '\t', 'V', '\x3', 
		'\x2', '\x2', '\x2', '\v', '_', '\x3', '\x2', '\x2', '\x2', '\r', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\xF', 'g', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'i', '\x3', '\x2', '\x2', '\x2', '\x13', 'k', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'm', '\x3', '\x2', '\x2', '\x2', '\x17', 'o', '\x3', '\x2', '\x2', 
		'\x2', '\x19', 'q', '\x3', '\x2', '\x2', '\x2', '\x1B', 't', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', 'y', '\x3', '\x2', '\x2', '\x2', '\x1F', '~', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x83', '\x3', '\x2', '\x2', '\x2', '#', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '%', '\x89', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', ')', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '+', '\x91', '\x3', '\x2', '\x2', '\x2', '-', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x31', '\xA1', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x37', '\xB3', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xB6', '\x3', '\x2', '\x2', '\x2', ';', '\xBB', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xBD', '\x3', '\x2', '\x2', '\x2', '?', 
		'\x41', '\x5', '\x5', '\x3', '\x2', '@', '?', '\x3', '\x2', '\x2', '\x2', 
		'@', '\x41', '\x3', '\x2', '\x2', '\x2', '\x41', '\x44', '\x3', '\x2', 
		'\x2', '\x2', '\x42', '\x45', '\x5', '\a', '\x4', '\x2', '\x43', '\x45', 
		'\x5', '\t', '\x5', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x46', 'I', '\x5', '\r', '\a', '\x2', 'G', 'I', '\x5', 
		'\xF', '\b', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 'G', 
		'\x3', '\x2', '\x2', '\x2', 'I', '\x6', '\x3', '\x2', '\x2', '\x2', 'J', 
		'U', '\x5', '\x1B', '\xE', '\x2', 'K', 'L', '\x5', '\x11', '\t', '\x2', 
		'L', 'M', '\x5', '\x1F', '\x10', '\x2', 'M', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'O', '\x5', '\x13', '\n', '\x2', 'O', 'P', '\x5', '!', '\x11', 
		'\x2', 'P', 'U', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x5', '\x15', 
		'\v', '\x2', 'R', 'S', '\x5', '\x1D', '\xF', '\x2', 'S', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'T', 'J', '\x3', '\x2', '\x2', '\x2', 'T', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'T', 'N', '\x3', '\x2', '\x2', '\x2', 'T', 'Q', '\x3', '\x2', 
		'\x2', '\x2', 'U', '\b', '\x3', '\x2', '\x2', '\x2', 'V', 'Z', '\x5', 
		'\x1B', '\xE', '\x2', 'W', 'X', '\x5', '\x17', '\f', '\x2', 'X', 'Y', 
		'\x5', '\x1B', '\xE', '\x2', 'Y', '[', '\x3', '\x2', '\x2', '\x2', 'Z', 
		'W', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', 
		'[', ']', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\x5', '\v', '\x6', '\x2', 
		']', '\\', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', 
		'\x2', '^', '\n', '\x3', '\x2', '\x2', '\x2', '_', '\x61', '\x5', '\x19', 
		'\r', '\x2', '`', '\x62', '\x5', '\x5', '\x3', '\x2', '\x61', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x5', '\x1B', '\xE', 
		'\x2', '\x64', '\f', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', 
		'-', '\x2', '\x2', '\x66', '\xE', '\x3', '\x2', '\x2', '\x2', 'g', 'h', 
		'\a', '/', '\x2', '\x2', 'h', '\x10', '\x3', '\x2', '\x2', '\x2', 'i', 
		'j', '\a', '&', '\x2', '\x2', 'j', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'k', 'l', '\a', '(', '\x2', '\x2', 'l', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\a', '\'', '\x2', '\x2', 'n', '\x16', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\a', '\x30', '\x2', '\x2', 'p', '\x18', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'r', '\t', '\x2', '\x2', '\x2', 'r', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', 's', 'u', '\x5', '#', '\x12', '\x2', 't', 's', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', 'x', 'z', '\x5', ')', '\x15', '\x2', 'y', 
		'x', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', 
		'{', 'y', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x3', '\x2', '\x2', '\x2', 
		'|', '\x1E', '\x3', '\x2', '\x2', '\x2', '}', '\x7F', '\x5', '%', '\x13', 
		'\x2', '~', '}', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', 
		'\x3', '\x2', '\x2', '\x2', '\x81', ' ', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x84', '\x5', '\'', '\x14', '\x2', '\x83', '\x82', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\t', '\x3', '\x2', 
		'\x2', '\x88', '$', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\t', 
		'\x4', '\x2', '\x2', '\x8A', '&', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'\x8C', '\t', '\x5', '\x2', '\x2', '\x8C', '(', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '\x8E', '\t', '\x6', '\x2', '\x2', '\x8E', '*', '\x3', '\x2', 
		'\x2', '\x2', '\x8F', '\x92', '\x5', '-', '\x17', '\x2', '\x90', '\x92', 
		'\x5', '/', '\x18', '\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', 
		'\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x98', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x97', '\x5', '-', '\x17', '\x2', '\x94', '\x97', 
		'\x5', '#', '\x12', '\x2', '\x95', '\x97', '\x5', '/', '\x18', '\x2', 
		'\x96', '\x93', '\x3', '\x2', '\x2', '\x2', '\x96', '\x94', '\x3', '\x2', 
		'\x2', '\x2', '\x96', '\x95', '\x3', '\x2', '\x2', '\x2', '\x97', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', '\x98', '\x96', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', ',', '\x3', '\x2', 
		'\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', 
		'\t', '\a', '\x2', '\x2', '\x9C', '.', '\x3', '\x2', '\x2', '\x2', '\x9D', 
		'\x9E', '\a', '\x61', '\x2', '\x2', '\x9E', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA2', '\x5', '\x33', '\x1A', '\x2', '\xA0', '\xA2', '\x5', 
		'\x37', '\x1C', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\x32', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xAC', '\x5', '\x35', '\x1B', '\x2', '\xA6', '\xAB', '\n', '\b', '\x2', 
		'\x2', '\xA7', '\xA8', '\x5', '\x35', '\x1B', '\x2', '\xA8', '\xA9', '\x5', 
		'\x35', '\x1B', '\x2', '\xA9', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\x5', '\x35', '\x1B', '\x2', '\xB0', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xB2', '\a', ')', '\x2', '\x2', '\xB2', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\x5', '\x39', '\x1D', 
		'\x2', '\xB4', '\xB5', '\x5', '\t', '\x5', '\x2', '\xB5', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xB6', '\xB7', '\a', '%', '\x2', '\x2', '\xB7', 
		':', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBC', '\x5', '-', '\x17', '\x2', 
		'\xB9', '\xBC', '\x5', '#', '\x12', '\x2', '\xBA', '\xBC', '\x5', '%', 
		'\x13', '\x2', '\xBB', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', 
		'\x3', '\x2', '\x2', '\x2', '\xBB', '\xBA', '\x3', '\x2', '\x2', '\x2', 
		'\xBC', '<', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBE', '\t', '\t', '\x2', 
		'\x2', '\xBE', '>', '\x3', '\x2', '\x2', '\x2', '\x16', '\x2', '@', '\x44', 
		'H', 'T', 'Z', ']', '\x61', 'v', '{', '\x80', '\x85', '\x91', '\x96', 
		'\x98', '\xA1', '\xA3', '\xAA', '\xAC', '\xBB', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
